export class ProfileResponse {
    httpStatus?: string
    message?: string
    data?: Data
}

export class Data {
    ementityid?: string
    emname?: string
    emphoneno1?: any
    emphoneno2?: any
    emedemailid?: string
    emedmobilenumber?: string
    emedemailfrequency?: any
    emednomineename?: any
    emednomineerelation?: any
    empanno?: string
    emedgender?: string
    umuserid?: string
    emedcustomerid?: any
    dpInfo?: any
    banklist?: Banklist[]
    nomineedetails?: Nomineedetails
    umementityid?: string
    umusertype?: string
    umupprofileid?: string
    acctype?: string
    customerId?: any
    emclienttype?: string
    emdob?: string
    nominee?: any
    maritalStatus?: any
    emloginid?: string
}

export class Banklist {
    ebdaccnumber?: string
    ebdbmbankcode?: string
    ebdementityid?: string
    ebdstatus?: string
    ebdcompanyid?: any
    ebdacctype?: string
    ebdacccustomerid?: string
    ebddefaultac?: string
    ebdcreatedby?: string
    ebdcreateddate?: string
    ebdupdateby?: any
    ebdupdatedate?: any
    ebdbranchcode?: any
    ebdresstatus?: string
    ebducccode?: any
    ebdpoaeligibility?: string
    ebdifsccode?: string
}

export class Nomineedetails {
    endentid?: any
    endnomdtlsreqr?: any
    endnomineename?: any
    endnomineepan?: any
    endnomdob?: any
    endnomguardian?: any
    endnomnationality?: any
    endnomproofofidentity?: any
    endnomaddressline7?: any
    endnomaddressline6?: any
    endnomaddressline5?: any
    endnomaddressline4?: any
    endnomaddressline3?: any
    endnomaddressline2?: any
    endnomguardphone?: any
    endnomguaraddress?: any
    endnomphoneno?: any
    endnomaddressline1?: any
    endnomrltn?: any
    endnomshareperc?: any
    endnomemailid?: any
    endnomguaremailid?: any
    endnom2dtlsreqr?: any
    endnominee2name?: any
    endnominee2pan?: any
    endnom2dob?: any
    endnom2guardian?: any
    endnom2nationality?: any
    endnom2proofofidentity?: any
    endnom2addressline7?: any
    endnom2addressline6?: any
    endnom2addressline5?: any
    endnom2addressline4?: any
    endnom2addressline3?: any
    endnom2addressline2?: any
    endnom2guardphone?: any
    endnom2guaraddress?: any
    endnom2phoneno?: any
    endnom2addressline1?: any
    endnom2rltn?: any
    endnom2shareperc?: any
    endnom2emailid?: any
    endnom2guaremailid?: any
    endnom3dtlsreqr?: any
    endnominee3name?: any
    endnominee3pan?: any
    endnom3dob?: any
    endnom3guardian?: any
    endnom3nationality?: any
    endnom3proofofidentity?: any
    endnom3addressline7?: any
    endnom3addressline6?: any
    endnom3addressline5?: any
    endnom3addressline4?: any
    endnom3addressline3?: any
    endnom3addressline2?: any
    endnom3guardphone?: any
    endnom3guaraddress?: any
    endnom3phoneno?: any
    endnom3addressline1?: any
    endnom3rltn?: any
    endnom3shareperc?: any
    endnom3emailid?: any
    endnom3guaremailid?: any
    endcreatedt?: any
    endcreateby?: any
    endlastupdtdt?: any
    endlastupdtby?: any
    endprgid?: any
    endnomguardrltn?: any
    endguardproofofidentity?: any
    endnom2guardrltn?: any
    endguard2proofofidentity?: any
    endnom3guardrltn?: any
    endguard3proofofidentity?: any
}
